// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YtgmXz_RxhT5JcSfnI7fJWgkHh6aO7E',
    appId: '1:350056430506:ios:e733e4f6c1ad0fc7dc89d3',
    messagingSenderId: '350056430506',
    projectId: 'notetakeapp-18b01',
    storageBucket: 'notetakeapp-18b01.firebasestorage.app',
    iosBundleId: 'com.example.notetakeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_YtgmXz_RxhT5JcSfnI7fJWgkHh6aO7E',
    appId: '1:350056430506:ios:e733e4f6c1ad0fc7dc89d3',
    messagingSenderId: '350056430506',
    projectId: 'notetakeapp-18b01',
    storageBucket: 'notetakeapp-18b01.firebasestorage.app',
    iosBundleId: 'com.example.notetakeapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-dnBHSn-03wUidYiKkyWwLbeeNi95t6k',
    appId: '1:350056430506:web:a55b85f6db49d733dc89d3',
    messagingSenderId: '350056430506',
    projectId: 'notetakeapp-18b01',
    authDomain: 'notetakeapp-18b01.firebaseapp.com',
    storageBucket: 'notetakeapp-18b01.firebasestorage.app',
    measurementId: 'G-Y16553FCB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCfFDWir0I4K_tmfnzKmZpt4jxixLA8pE',
    appId: '1:350056430506:android:6ce578620d4c27f2dc89d3',
    messagingSenderId: '350056430506',
    projectId: 'notetakeapp-18b01',
    storageBucket: 'notetakeapp-18b01.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-dnBHSn-03wUidYiKkyWwLbeeNi95t6k',
    appId: '1:350056430506:web:0b96617ed5ca5b20dc89d3',
    messagingSenderId: '350056430506',
    projectId: 'notetakeapp-18b01',
    authDomain: 'notetakeapp-18b01.firebaseapp.com',
    storageBucket: 'notetakeapp-18b01.firebasestorage.app',
    measurementId: 'G-X5FMR8VRLM',
  );

}